eureka:
  instance:
    hostname: localhost
    instance-id:  http://localhost:9099
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 9099
zuul:
  routes:
    service0: /service/0/**
    service1: /service/1/**


